
---1. VISTA PERSONA NATURAL
--SELECT*FROM V_PERSONA_N
CREATE VIEW V_PERSONA_N WITH ENCRYPTION
AS
SELECT	
		P.NombrePersona AS [NOMBRE],
		PN.DNI AS [DNI],
		PN.Sexo AS [SEXO],
		P.Telefono		
		FROM PERSONA P
		INNER JOIN PERSONA_NATURAL PN
			ON  P.IdPersona = PN.IdPersona
GO

--2.VISTA PERSONA JURIDICA
--SELECT*FROM V_PERSONA_J
CREATE VIEW V_PERSONA_J WITH ENCRYPTION
AS
SELECT
		RS.DescripcionRazon AS [RAZÓN SOCIAL],
		P.NombrePersona AS [NOMBRE],
		PJ.RUC,
		P.Telefono AS [TELEFONO]
		FROM PERSONA P
		INNER JOIN PERSONA_JURIDICA PJ
			ON P.IdPersona = PJ.IdPersona
		INNER JOIN RAZON_SOCIAL RS
			ON PJ.IdRazon=RS.IdRazon
GO




--3.VISTA PROGRAMACION MANTENIMIENTO
--SELECT*FROM V_MANTENIMIENTO
	CREATE VIEW V_MANTENIMIENTO WITH ENCRYPTION
	AS
	SELECT
		M.Fechamantenimiento AS [FECHA MANTENIMINETO],
		M.CostoMantenimiento AS [COSTO MANTENIMIENTO],
		R.DescrpcionRubro AS [RUBRO],
		E.NombreEmpresa AS [EMPRESA],
		E.Viaticos AS [VIATICOS EMPRESA],
		E.RUC,
		E.FFundacion AS [FUNDACION EMPRESA]
	
		FROM MANTENIMIENTO M
			INNER JOIN EMPRESA E
				ON M.IdEmpresa=E.IdEmpresa
			INNER JOIN RUBRO R
				ON E.IdRubro	= R.IdRubro
			
	GO
	   

--4.VISTA EMPLEADOS
--SELECT*FROM V_EMPLEADOS
CREATE VIEW V_EMPLEADOS WITH ENCRYPTION
 AS
 SELECT
		ES.NombreE AS [NOMBRE],
		ES.ApellidoE AS [APELLIDOS],
		ES.DNIE AS [DNI],
		TP.Descripcion AS [PUESTO],
		ES.Sueldo AS [SUELDO],
		ES.TelefonoE AS [TELEFONO],
		CONVERT(VARCHAR,ES.FInicio,103) AS [INICIO CONTRATO],
		CONVERT(VARCHAR,ES.FFin,103) AS [FIN CONTRATO]
		FROM EMPLEADO_SEGURIDAD ES
		INNER JOIN TIPO_SEGURIDAD TP
			ON ES.IdEmpleado = TP.IdTipo

 GO
 

--5.VISTA ATENCION VICTIMAS
--SELECT*FROM V_VICTIMAS_MUJERES
	CREATE VIEW V_VICTIMAS_MUJERES WITH ENCRYPTION
	AS
	SELECT	
			convert(varchar,S.Fecha,111) AS [FECHA],
			S.Hora AS [HORA],
			V.NombreVictima AS [NOMBRE],
			V.ApellidoPaternoVictima[APELLIODS],
			V.DNI,
			CONVERT(VARCHAR,V.FNacimiento,103) AS [NACIMIENTO],
			DATEDIFF(YEAR,V.FNacimiento,GETDATE()) AS [EDAD],
			V.Sexo AS [SEXO],
			D.DescripcionDelito AS [DELITO],
			E.Descripcion AS [ESTADO VICTIMA]
	FROM SERVICIO S 
	INNER JOIN ATENCION_VICTIMAS	A
		ON S.IdPersona =	A.IdServicio
	INNER JOIN VICTIMA V
		ON A.IdVictima =V.IdVictima
	INNER JOIN DELITO D
		ON A.idDelito=D.idDelito
	INNER JOIN ESTADO_VICTIMA E
		ON V.IdEstado=E.IdEstado	
		where V.Sexo = 'M'
	GO

	

--6.VISTA VIDEOVIGILANCIA
--SELECT*FROM V_VIDEOVIGILANCIA
	CREATE VIEW V_VIDEOVIGILANCIA WITH ENCRYPTION
	AS
	SELECT
		CONVERT(VARCHAR,S.Fecha,103) AS [FECHA],
		S.Hora AS [HORA],
		O.NombreVO AS [VIDEOPERADOR],
		TC.Descripcion [TIPO DE CAMARA],
		C.Marca AS [MARCA],
		C.AñoFabricacion AS [AÑO FABRICACIÓN],
		C.Ubicacion
		FROM SERVICIO S
		INNER JOIN VIDEOVIGILANCIA V
			ON S.IdServicio = V.IdServicio
		INNER JOIN VIDEO_OPERADOR O
			ON V.IdVO = O.IdVO
		INNER JOIN DETALLE_CAMARA DE
			ON V.IdVigilancia = DE.IdVigilancia
		INNER JOIN CAMARA C
			ON DE.IdCamara =  C.IdCamara
		INNER JOIN TIPO_CAMARA	TC
			ON C.IdTipoCamara = TC.IdTipoCamara
	GO

	

--7.VISTA SERVICIO
--SELECT*FROM V_SERVICIO
	CREATE VIEW V_SERVICIO WITH ENCRYPTION
	AS
	SELECT 
		CONVERT(VARCHAR,S.Fecha,103) AS [FECHA],
		S.Hora AS [HORA],
		TP.Descripcion,
		E.DescripcionEstado AS [ESTADO SERVCICIO],
		S.Numero AS [NUMÉRO TELEFONICO],
		C.DetalleTipoDescripcion AS	[TIPO COMUNICACION]
		
	FROM SERVICIO S
	INNER JOIN TIPO_SERVICIO TP
				ON S.IdTipoServicio = TP.IdTipoServicio

	INNER JOIN ESTADO_SERVICIO E
		ON S.IdEstado = E.IdEstado
	INNER JOIN TIPO_COMUNICACION C
	ON S.IdTipoDescripcion = C.IdTipoDescripcion

	GO
	

	SELECT*
			FROM SERVICIO S
			INNER JOIN TIPO_SERVICIO TP
				ON S.IdTipoServicio = TP.IdTipoServicio

GO

--8.VISTA EVALUACION DE SERENAZGO
--SELECT*FROM V_SERENAZGO_SE
	CREATE VIEW V_SERENAZGO_SE WITH ENCRYPTION
	AS
	SELECT
		S.NombreSereno AS [NOMBRE],
		S.ApellidoSereno AS [APELLIDOS],
		S.DNISerenazgo,
		CONVERT(VARCHAR,S.FechaNacimientoSereno,103) AS [FEHCA NACIMIENTO],
		DATEDIFF(YEAR,S.FechaNacimientoSereno,GETDATE() ) AS [EDAD],
		S.Sexo AS [SEXO]
			FROM SERENAZGO S
	INNER JOIN DETALLE_SERENAZGO D
		ON S.IdSerenazgo = D.IdSerenazgo
	INNER JOIN SERVICIO SE
		ON SE.IdServicio = D.IdServicio
	INNER JOIN MUNICIPALIDAD M
		ON M.IdMunicipalidad = SE.IdMunicipalidad
	
	GO

--9.VISTA PREVENCION DE DELITO
--SELECT*FROM V_PREVENCION
	CREATE VIEW V_PREVENCION WITH ENCRYPTION
		AS
		SELECT 
	CONVERT(VARCHAR,S.Fecha,103) AS [FECHA],
	S.Hora AS [HORA],
	D.Ubicacion AS [UBICACIÓN],
	PD.Detalle AS [DETALLE],
	P.NombrePolicia AS [NOMBRE],
	P.ApellidoPaterno AS [APELLIDO PATERNO],
	P.ApellidoPaterno AS [APELLIDO MATERNO],
	R.DescripcionRango AS [RANGO],
	P.DNIPM AS [DNI],
	P.Sexo AS [SEXO],
	CONVERT(VARCHAR,P.FechaInicioServicio,103) AS [INICIO SERVICIO],
		C.Nombre AS [NOMBRE COMISARIA]

	FROM DELINCUENCIAL D
	INNER JOIN PREVENCION_DELITO PD
		ON D.IdDelicuencial=PD.IdDelicuencial
	INNER JOIN SERVICIO S
	ON S.IdServicio = D.IdServicio
	INNER JOIN ESTADO_SERVICIO E
		ON S.IdEstado=E.IdEstado
	INNER JOIN TIPO_COMUNICACION T
		ON S.IdTipoDescripcion = T.IdTipoDescripcion
	INNER JOIN DETALLE_POLICIA DP
	ON  D.IdDelicuencial = DP.IdDelicuencial
	INNER JOIN POLICIA P 
	ON DP.IdPolicia=P.IdPolicia
	INNER JOIN RANGO_POLICIA R
	ON P.IdRango = R.IdRango
	INNER JOIN COMISARIA C
	ON P.IdComisaria = C.IdComisaria
	GO
	


--10.VISTA PERSECUCCION
--SELECT*FROM V_PERSECUCION
	CREATE VIEW V_PERSECUCION WITH ENCRYPTION
	AS
	SELECT 
	CONVERT(VARCHAR,S.Fecha,103) AS [FECHA],
	S.Hora AS [HORA],
	D.Ubicacion AS [UBICACIÓN],
	CP.Detalle AS [DETALLE],
	P.NombrePolicia AS [NOMBRE],
	P.ApellidoPaterno AS [APELLIDO PATERNO],
	P.ApellidoPaterno AS [APELLIDO MATERNO],
	R.DescripcionRango AS [RANGO],
	P.DNIPM AS [DNI],
	P.Sexo AS [SEXO],
		C.Nombre AS [NOMBRE COMISARIA]

	FROM DELINCUENCIAL D
	INNER JOIN CONTROL__PERSECUCCION CP
		ON D.IdDelicuencial=CP.IdDelicuencial
	INNER JOIN SERVICIO S
	ON S.IdServicio = D.IdServicio
	INNER JOIN ESTADO_SERVICIO E
		ON S.IdEstado=E.IdEstado
	INNER JOIN TIPO_COMUNICACION T
		ON S.IdTipoDescripcion = T.IdTipoDescripcion
	INNER JOIN DETALLE_POLICIA DP
	ON  D.IdDelicuencial = DP.IdDelicuencial
	INNER JOIN POLICIA P 
	ON DP.IdPolicia=P.IdPolicia
	INNER JOIN RANGO_POLICIA R
	ON P.IdRango = R.IdRango
	INNER JOIN COMISARIA C
	ON P.IdComisaria = C.IdComisaria
	GO
	SELECT * FROM V_PERSECUCION
	SELECT * FROM V_PREVENCION
	GO
	
--11. VISTA SUJETOS
--SELECT*FROM V_SUJETOS
CREATE VIEW V_SUJETOS
AS
SELECT 
E.NombreE [NOMBRE],LEFT(E.ApellidoE,CHARINDEX(' ',E.ApellidoE)-1)  [APELLIDO],E.DNIE  [DNI],'EMPLEADO' AS [SUJETO]FROM EMPLEADO_SEGURIDAD E
 UNION  ALL
SELECT  
S.NombreSereno [NOMBRE],LEFT(S.ApellidoSereno,CHARINDEX(' ',S.ApellidoSereno)-1)  [APELLIDO],S.DNISerenazgo AS [DNI],'SERENO' AS [SUJETO]FROM SERENAZGO S
UNION ALL
SELECT 
P.NombrePolicia [NOMBRE],P.ApellidoPaterno,P.DNIPM,'POLICIA' AS [SUJETO] FROM POLICIA P
UNION ALL
SELECT 
LEFT(PE.NombrePersona,CHARINDEX(' ',PE.NombrePersona)-1)  [NOMBRE],SUBSTRING(PE.NombrePersona,CHARINDEX(' ',PE.NombrePersona)+1,LEN(PE.NombrePersona)) [APELLIDO],N.DNI,
		'PERSONA NATURAL' AS [SUJETO] FROM PERSONA PE INNER JOIN PERSONA_NATURAL N	ON PE.IdPersona=N.IdPersona
UNION ALL
SELECT 
V.NombreVictima [NOMBRE],LEFT(V.ApellidoPaternoVictima,CHARINDEX(' ',V.ApellidoPaternoVictima)-1)  [APELLIDO],V.DNI,'VICTIMA' AS [SUJETO]FROM VICTIMA V
GO