-------------------------FUNCIONES ESCALARES--------------------
--1.SUELDO NETO EMPLEADO  
--SELECT dbo.F_SUELDO_NETO(1)
CREATE FUNCTION F_SUELDO_NETO(
@IDEMPLEADO INT 
)
 RETURNS SMALLMONEY
AS
BEGIN

 DECLARE @SUELDO SMALLMONEY
	SET @SUELDO = (SELECT E.Sueldo FROM EMPLEADO_SEGURIDAD E WHERE E.IdEmpleado =@IDEMPLEADO ) 

DECLARE @ESSALUD SMALLMONEY	
	SET @ESSALUD = (@SUELDO ) * 0.09

DECLARE @PENSION SMALLMONEY 
	SET @PENSION= (@SUELDO) * 0.1

DECLARE @SUELDONETO SMALLMONEY
SET @SUELDONETO = ((@SUELDO) - @ESSALUD - @PENSION) 

IF(@SUELDONETO IS NULL)
SET @SUELDONETO=0
RETURN @SUELDONETO
END
GO


--2. DEVALUACIÓN ANUAL PATRULLA
--SELECT dbo.PRECIO_ACTUAL_VEHICULO(1)
CREATE FUNCTION PRECIO_ACTUAL_VEHICULO(
@IDPATRULLA INT
)
RETURNS SMALLMONEY
AS
BEGIN

DECLARE @AÑOS INT
SET @AÑOS= DATEDIFF(YEAR,CAST((SELECT V.Año FROM VEHICULOS V INNER JOIN TIPO_VEHICULO T ON V.IdTipoV= T.IdTipoV WHERE V.IdPatrulla=@IDPATRULLA  ) AS DATETIME),GETDATE())

DECLARE @PORCENTAJE SMALLMONEY
	SET @PORCENTAJE = ((SELECT V.Costo FROM VEHICULOS V INNER JOIN TIPO_VEHICULO T ON V.IdTipoV= T.IdTipoV WHERE V.IdPatrulla=@IDPATRULLA) * 0.05)

DECLARE @DEVALUACION SMALLMONEY
 SET @DEVALUACION = (SELECT V.Costo FROM VEHICULOS V INNER JOIN TIPO_VEHICULO T ON V.IdTipoV= T.IdTipoV WHERE V.IdPatrulla=@IDPATRULLA)  - (@PORCENTAJE * @AÑOS)

 if (@DEVALUACION IS NULL)


SET @DEVALUACION =0
RETURN @DEVALUACION
END 
GO

--3. PRECIO NETO DE UN MANTENIMIENTO
--SELECT dbo.F_PRECIO_NETO_MANETIMIENTO(1)
CREATE FUNCTION F_PRECIO_NETO_MANETIMIENTO(
@IDMATENIMIENTO int
)
RETURNS INT
AS
BEGIN
DECLARE @IGV FLOAT
SET @IGV =(( SELECT M.CostoMantenimiento  FROM PROGRAMACIÓN P
										INNER JOIN MANTENIMIENTO M
										ON P.IdMantenimiento = M.IdMantenimiento
							where M.IdMantenimiento=@IDMATENIMIENTO) * 0.18)


DECLARE @PRECIONETO FLOAT
SET @PRECIONETO =( SELECT M.CostoMantenimiento  FROM  MANTENIMIENTO M where M.IdMantenimiento= @IDMATENIMIENTO)+
					@IGV + (SELECT E.Viaticos
								FROM PROGRAMACIÓN P
									INNER JOIN MANTENIMIENTO M	
										ON P.IdMantenimiento = M.IdMantenimiento 
									INNER JOIN EMPRESA E
										ON M.IdEmpresa = E.IdEmpresa
										WHERE P.idProgramacion= @IDMATENIMIENTO )
	
if (@PRECIONETO IS NULL)


SET @PRECIONETO =0
RETURN @PRECIONETO
END 
GO