------------------------FUNCIONES DE TABLA----------------

--1. BUSCAR A PERSONA POR DNI O NOMBRE
--select*from F_PERSONA_NATURAL('74851236')

CREATE FUNCTION  F_PERSONA_NATURAL (
@BUSCAR VARCHAR(50)
)
RETURNS @PNATURAL TABLE(NombrePersona VARCHAR(50),DNI CHAR(08),Sexo CHAR(01),Telefono char(09)
)
AS
BEGIN
IF EXISTS( SELECT*FROM V_PERSONA_N WHERE NOMBRE =@BUSCAR OR DNI=@BUSCAR)
INSERT @PNATURAL SELECT*FROM V_PERSONA_N WHERE NOMBRE=@BUSCAR or DNI=@BUSCAR

ELSE

INSERT @PNATURAL SELECT*FROM V_PERSONA_N

RETURN

END
GO

--2. BUSCAR UNA PERSONA JURICA POR RAZON,RUC O NOMBRE
--SELECT*FROM  F_PERSONA_JURIDICA('FERTILIZANTES')

CREATE  FUNCTION  F_PERSONA_JURIDICA(
@BUSCAR VARCHAR(50)
) 
RETURNS @PJURIDICA TABLE(DescripcionRazon varchar(50),NombrePersona varchar(50),RUC VARCHAR(11),Telefono char(09)
)
AS
BEGIN
	IF EXISTS(SELECT*FROM V_PERSONA_J WHERE [RAZÓN SOCIAL]=@BUSCAR OR NOMBRE=@BUSCAR OR RUC=@BUSCAR)
	INSERT @PJURIDICA SELECT * FROM V_PERSONA_J WHERE  [RAZÓN SOCIAL]=@BUSCAR OR NOMBRE=@BUSCAR OR RUC=@BUSCAR
ELSE

INSERT @PJURIDICA SELECT * FROM V_PERSONA_J

RETURN
END
GO


--3. BUSCAR EMPLEADO POR DNI
--SELECT*FROM F_EMPLEADOS('70408123')
CREATE FUNCTION F_EMPLEADOS(
@BUSCAR VARCHAR (50)
)
RETURNS @EMPLEADO TABLE(NombreE varchar(50),ApellidoE varchar(50),DNIE char(08),Descripcion varchar(50),Sueldo int,Telefono varchar(09),FInicio date,FFin date)
AS
BEGIN
	IF EXISTS(SELECT*FROM V_EMPLEADOS WHERE  DNI=@BUSCAR)
	INSERT @EMPLEADO SELECT * FROM V_EMPLEADOS WHERE  DNI=@BUSCAR
ELSE
	INSERT @EMPLEADO SELECT * FROM V_EMPLEADOS

RETURN
END
GO
