-----------------------PROCEDMIENTOS ALMACENADOS-------------------
--1. SP TIPO SELECT:INGRESARA EL AÑO Y MOSTRAR LOS SERVICIOS RALIZADOS A LO LARGO DE TODOS LOS MESES DEL AÑO
--EXEC SP_SERVICIOS '2017'

ALTER PROC SP_SERVICIOS(
@AÑO CHAR(04)
)
AS
BEGIN
IF EXISTS (SELECT TOP 1  S.IdServicio FROM SERVICIO S WHERE YEAR(S.Fecha)= @AÑO)
BEGIN 
SELECT
		[AÑO DEL SERVICIO],
		[TIPO DE SERVICIO] ,
		ISNULL([1],0) AS Enero,
		ISNULL([2],0) AS Febrero,
		ISNULL([3],0) AS Marzo,
		ISNULL([4],0) AS Abril,
		ISNULL([5],0) AS Mayo,
		ISNULL([6],0) AS Junio,
		ISNULL([7],0) AS Julio,
		ISNULL([8],0) AS Agosto,
		ISNULL([9],0) AS Setiembre,
		ISNULL([10],0) AS Octubre,
		ISNULL([11],0) AS Noviembre,
		ISNULL([12],0) AS Diciembre,
		(ISNULL([1],0) + ISNULL([2],0) + ISNULL([3],0) + ISNULL([4],0) + ISNULL([5],0) + ISNULL([6],0) + ISNULL([7],0)
		+ ISNULL([8],0) + ISNULL([9],0) + ISNULL([10],0) + ISNULL([11],0) + ISNULL([12],0)) [TOTAL SERVICIOS]
FROM
(
	SELECT
		YEAR(S.Fecha) AS [AÑO DEL SERVICIO],
			TP.Descripcion AS [TIPO DE SERVICIO],
			DATEPART(MONTH,S.Fecha) AS [MESES],
			S.IdServicio AS [CANTIDAD]

	FROM	SERVICIO S
		INNER JOIN TIPO_SERVICIO TP
			ON S.IdTipoServicio= TP.IdTipoServicio
			WHERE YEAR(S.Fecha)=@AÑO
	)AS Data PIVOT(COUNT(CANTIDAD) FOR Meses IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12])) as pvt ORDER BY [TIPO DE SERVICIO] 
END
ELSE
BEGIN
SELECT 0 as Resultado
END
END


---2. SP TIPO INSERT: PARA INSERTAR UNA PERSONA NATURAL
--EXEC SP_PERSONA_N 'ARCE MACHUCA','948987665','SIN DETALLE ALGUNO','73772919','M'
ALTER PROC SP_PERSONA_N(
@NOMBREPERSONA VARCHAR(50),
@TELEFONO CHAR(09),
@DETALLEDENUNCIA VARCHAR(50),
@DNI CHAR(08),
@SEXO CHAR(01)
)
AS
SET NOCOUNT ON
IF NOT EXISTS(SELECT TOP 1 N.IdPersona FROM PERSONA_NATURAL N WHERE N.DNI = @DNI)
BEGIN

	INSERT INTO PERSONA(NombrePersona,Telefono,DettalleDenuncia)
	VALUES(@NOMBREPERSONA,@TELEFONO,@DETALLEDENUNCIA) 

		 DECLARE @PERSONA INT
	 SET @PERSONA = @@IDENTITY


	INSERT INTO PERSONA_NATURAL(IdPersona,DNI,Sexo)
	 VALUES(@PERSONA,@DNI,@SEXO)
	 

	 PRINT 'PERSONA NATURAL REGISTRADO CON EXITO'
END
ELSE
BEGIN
	PRINT 'EL PRESONA NATURAL YA EXISTE'
	RETURN
END


-----3. SP TIPO INSERT: PARA INGRESAR UNA PERSONA JURIDICA
--EXEC SP_PERSONA_J 'MANUELITA S.A.','96582457','SIN DETALLES','7856324896520153',6
CREATE PROC SP_PERSONA_J(
@NOMBREPERSONA VARCHAR(50),
@TELEFONO CHAR(09),
@DETALLEDENUNCIA VARCHAR(09),
@RUC CHAR(11),
@IDRAZON INT
)
AS
SET NOCOUNT ON
IF NOT EXISTS(SELECT TOP 1  J.IdPersona FROM PERSONA_JURIDICA J WHERE J.RUC=@RUC)
BEGIN
	INSERT INTO PERSONA(NombrePersona,Telefono,DettalleDenuncia)
	VALUES(@NOMBREPERSONA,@TELEFONO,@DETALLEDENUNCIA) 

	DECLARE @AUXPERSONA INT
	SET @AUXPERSONA = @@IDENTITY

	INSERT INTO PERSONA_JURIDICA(IdPersona,RUC,IdRazon)
	VALUES (@AUXPERSONA,@RUC,@IDRAZON)

	 PRINT 'PERSONA JURIDICA REGISTRADO CON EXITO'
END
ELSE
BEGIN
	PRINT 'EL PRESONA JURIDICA YA EXISTE'
	RETURN
END


--4.SPA PARA INGRESAR VICTIMAS
--EXEC SP_VICTIMA 'WILLIAM','HUAMAN','73291819','M','19990318',3
CREATE PROC SP_VICTIMA (
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50),
@DNI CHAR(08),
@SEXO CHAR(01),
@FNACIMIENTO DATE,
@IDESTADO INT
)AS
SET NOCOUNT ON
IF NOT EXISTS(SELECT TOP 1 V.IdVictima FROM VICTIMA V WHERE V.DNI=@DNI )
BEGIN
	INSERT INTO VICTIMA(NombreVictima,ApellidoPaternoVictima,DNI,Sexo,FNacimiento,IdEstado)
	VALUES (@NOMBRE,@APELLIDO,@DNI,@SEXO,@FNACIMIENTO,@IDESTADO)
	PRINT 'VICTIMA REGISTRADA'
	RETURN
END
ELSE
BEGIN
	PRINT 'LA VICTIMA YA EXISTE'
	RETURN

END


-------------5.SP PARA REGISTRAR UN NUEVO EMPLEADO-------
EXEC SP_EMPLEADO 'JUAN','BUENO','85632147','12368549',3,1000
CREATE PROC SP_EMPLEADO(
@NombreE varchar(50),
@ApellidoE varchar(50),
@DNIE char(08),
@TelefonoE char(09),
@IdTipo int,
@Sueldo int
)
AS
SET NOCOUNT ON
IF NOT EXISTS(SELECT TOP 1 E.IdEmpleado FROM EMPLEADO_SEGURIDAD E WHERE E.DNIE = @DNIE )
BEGIN
	INSERT INTO EMPLEADO_SEGURIDAD(NombreE,ApellidoE,DNIE,TelefonoE,FInicio,FFin,IdTipo,Sueldo)
	VALUES(@NombreE,@ApellidoE,@DNIE,@TelefonoE,GETDATE(),GETDATE() + 180,@IdTipo,@Sueldo)

	DECLARE @AUXIEMPLEADO INT
	SET @AUXIEMPLEADO = @@IDENTITY

	INSERT INTO AREA_SEGURIDAD(FFundacion,IdEmpleado,IdMunicipalidad)
	VALUES('10/01/1990',@AUXIEMPLEADO,1)
	
	PRINT 'EMPLEADO REGITRADO CON EXITO'
	RETURN
END
ELSE

BEGIN

PRINT 'EL EMPLEADO YA EXISTE'
RETURN
END


-------------6.SP PARA PROGRAMACION -------

--EXEC SP_PROGRAMACIÓN '8596324856321458','1980-06-21','PERICASO S.A.',200,2,'2021-11-20',5000,1
CREATE PROC SP_PROGRAMACIÓN (
@RUC CHAR(08),
@FFUNDACION DATE,
@NOMBREEMPRESA VARCHAR(50),
@VIATICO INT,
@IDRUBRO INT,
@FECHAMANTENIMIENTO DATE,
@COSTOMANTENIMIENTO INT,
@IDESTADOEVA INT
)
AS
SET NOCOUNT ON
IF NOT EXISTS(SELECT TOP 1 E.IdEmpresa FROM EMPRESA E WHERE E.RUC=@RUC AND E.NombreEmpresa=@NOMBREEMPRESA)
BEGIN
	INSERT INTO EMPRESA(RUC,FFundacion,NombreEmpresa,IdRubro,Viaticos)
	VALUES (@RUC,@FFUNDACION,@NOMBREEMPRESA,@IDRUBRO,@VIATICO)

	DECLARE @AUXIEMPRESA INT
	SET @AUXIEMPRESA = @@IDENTITY

	INSERT INTO MANTENIMIENTO(Fechamantenimiento,CostoMantenimiento,IdEmpresa)
	VALUES	(@FECHAMANTENIMIENTO,@COSTOMANTENIMIENTO,@AUXIEMPRESA)
	
	DECLARE @AUXIMANTNIMEINTO INT
	SET @AUXIMANTNIMEINTO=@@IDENTITY

	INSERT INTO EVALUACION(FechaEvaluacion,IdEstadoEva)
	VALUES(GETDATE()+ 15  ,@IDESTADOEVA)
	
	DECLARE @AUXIEVALUACION INT
	SET @AUXIEVALUACION= @@IDENTITY

	INSERT INTO PROGRAMACIÓN(IdMantenimiento,IdEvaluacion,IdMunicipalidad)
	VALUES(@AUXIMANTNIMEINTO,@AUXIEVALUACION,1)

	PRINT 'EMPRESA REGISTRADA CON EXITO'
END

ELSE
BEGIN

	PRINT 'LA EMPRESA YA EXISTE'
	RETURN
END




--7. SP PARA SERVICIO DE ATENCION VICTIMA---------------------------------------
--EXEC SP_S_VICTIMA 10,1,1,'963696521',3,2,'TOL-85ART'
CREATE PROC SP_S_VICTIMA (
 @IDPERSONA INT,
 @IDESTADO INT,
  @IDTIPO INT,
  @NUMERO CHAR(09),
 @IDVICTIMA INT,
 @IDELITO INT,
 @CODOPERACION CHAR(09)

)AS
SET NOCOUNT ON
IF NOT EXISTS( SELECT  TOP 1 A.IdAtencion  FROM  ATENCION_VICTIMAS   A WHERE  A.CodOperacion=@CODOPERACION  )
BEGIN
	INSERT INTO SERVICIO(IdMunicipalidad,Fecha,Hora,Numero,IdEstado,IdPersona,IdTipoDescripcion)
		VALUES (1,GETDATE(),CONVERT(CHAR(05),GETDATE(),108),@NUMERO,@IDESTADO, @IDPERSONA,@IDTIPO)

		DECLARE @AUXISERVICIO INT
			SET @AUXISERVICIO = @@IDENTITY

		INSERT INTO ATENCION_VICTIMAS(IdServicio,IdMunicipalidad,IdVictima,idDelito,CodOperacion)
			VALUES (@AUXISERVICIO,1,@IDVICTIMA,@IDELITO,@CODOPERACION)

			PRINT 'SERVICIO DE ATENCION A VICTIMA REGISTRADO'
			RETURN 

END

ELSE
BEGIN
	PRINT 'EL SERVICIO DE ATENCION A VICTIMA YA EXISTE'
	 RETURN
END

SELECT CONVERT(CHAR(05),GETDATE(),108)


--8.- SP PARA SERVICIO DE VIDEOVIGILANCIA----------------

EXEC SP_S_VIDEOVIGILANCIA 4,2,1,'854695824',3,'OKL-SDET9','SAMGUMG',3,'2021','PLAZA DE ARMAS'

CREATE PROC SP_S_VIDEOVIGILANCIA (
@IDPERSONA INT,
@IDESTADO INT,
@IDTIPO INT,
@NUMERO CHAR(09),
@IDOPERADOR INT,
@CODOPERACION CHAR(09),
@MARCA VARCHAR (50),
@IDTIPOCAMARA INT,
@AÑOFABRICACION CHAR(04),
@UBICACION VARCHAR(50)

)
AS
SET NOCOUNT ON
IF NOT EXISTS( SELECT  TOP 1 V.IdVigilancia   FROM   VIDEOVIGILANCIA V WHERE V.CodOperacion=@CODOPERACION  )
BEGIN
	INSERT INTO SERVICIO(IdMunicipalidad,Fecha,Hora,Numero,IdEstado,IdPersona,IdTipoDescripcion)
		VALUES (1,GETDATE(),CONVERT(CHAR(05),GETDATE(),108),@NUMERO,@IDESTADO, @IDPERSONA,@IDTIPO)
		
		DECLARE @AUXISERVICIO INT
		SET @AUXISERVICIO = @@IDENTITY

	INSERT INTO VIDEOVIGILANCIA(IdServicio,IdMunicipalidad,IdVO,CodOperacion)
		VALUES(@AUXISERVICIO,1,@IDOPERADOR,@CODOPERACION)
		
	DECLARE @AUXIVIDEO INT
	SET @AUXIVIDEO=@@IDENTITY

	INSERT INTO CAMARA(Marca,IdTipoCamara,AñoFabricacion,Ubicacion)
		VALUES (@MARCA,@IDTIPOCAMARA,@AÑOFABRICACION,@UBICACION)
		
	DECLARE @AUXICAMARA INT
		SET @AUXICAMARA = @@IDENTITY

		INSERT INTO DETALLE_CAMARA(IdVigilancia,IdServicio,IdMunicipalidad,IdCamara)
			VALUES(@AUXIVIDEO,@AUXISERVICIO,1,@AUXICAMARA)

			PRINT 'SERVICIO DE VIDEOVIGILANCIA REGISTRADO'
			RETURN 
END

ELSE
BEGIN
	PRINT 'EL SERVICIO DE VIDEOVIGILANCIA YA EXISTE'
	 RETURN
END




--9. SP PARA SERVICIO DE PREVENCION DELITO----------------
CREATE PROC SP_DELINCUENCIAL_PREVENCION (
@IDPERSONA INT,
@IDESTADO INT,
@IDTIPO INT,
@NUMERO CHAR(09),
@UBICACION VARCHAR(50),
@DETALLE VARCHAR(50),
@CODOPERACION CHAR(09),
@IDPOLICIA INT
)
AS
SET NOCOUNT ON
IF NOT EXISTS(SELECT TOP 1 P.IdPrevencion FROM PREVENCION_DELITO P WHERE P.CodOperacion= @CODOPERACION)
BEGIN
	INSERT INTO SERVICIO(IdMunicipalidad,Fecha,Hora,Numero,IdEstado,IdPersona,IdTipoDescripcion)
		VALUES (1,GETDATE(),CONVERT(CHAR(05),GETDATE(),108),@NUMERO,@IDESTADO, @IDPERSONA,@IDTIPO)
		
		DECLARE @AUXISERVICIO INT
		SET @AUXISERVICIO = @@IDENTITY

		INSERT INTO DELINCUENCIAL(IdServicio,IdMunicipalidad,Ubicacion,IdTipoDelincuencial)
			VALUES (@AUXISERVICIO,1,@UBICACION,1)

		DECLARE @AUXIDELINCUENCIA INT
		SET @AUXIDELINCUENCIA = @@IDENTITY

		INSERT INTO DETALLE_POLICIA(IdServicio,IdMunicipalidad,IdPolicia,IdDelicuencial)
		VALUES(@AUXISERVICIO,1,@IDPOLICIA,@AUXIDELINCUENCIA)

		INSERT INTO PREVENCION_DELITO(IdServicio,IdMunicipalidad,IdDelicuencial,Detalle,CodOperacion)
			VALUES(@AUXISERVICIO,1,@AUXIDELINCUENCIA,@DETALLE,@CODOPERACION)
					
					PRINT 'SERVICIO DE PREVENCION DELITO REGISTRADO'
						RETURN 

END
ELSE
BEGIN
	PRINT 'EL SERVICIO DE PREVENCION DELITO YA EXISTE'
	 RETURN
END


--10. SP PARA SERVICIO PERSECUCCIÓN----------------
CREATE PROC SP_DELINCUENCIAL_CONTROL_PERS(
@IDPERSONA INT,
@IDESTADO INT,
@IDTIPO INT,
@NUMERO CHAR(09),
@UBICACION VARCHAR(50),
@DETALLE VARCHAR(50),
@CODOPERACION CHAR(09),
@IDPOLICIA INT
)
AS
SET NOCOUNT ON
IF NOT EXISTS(SELECT TOP 1 C.IdControl FROM CONTROL__PERSECUCCION C WHERE C.CodOperación=@CODOPERACION)
BEGIN
	INSERT INTO SERVICIO(IdMunicipalidad,Fecha,Hora,Numero,IdEstado,IdPersona,IdTipoDescripcion)
		VALUES (1,GETDATE(),CONVERT(CHAR(05),GETDATE(),108),@NUMERO,@IDESTADO, @IDPERSONA,@IDTIPO)
		
		DECLARE @AUXISERVI INT
		SET @AUXISERVI = @@IDENTITY

		INSERT INTO DELINCUENCIAL(IdServicio,IdMunicipalidad,Ubicacion,IdTipoDelincuencial)
			VALUES (@AUXISERVI,1,@UBICACION,2)

		DECLARE @AUXIDELIN INT
		SET @AUXIDELIN = @@IDENTITY

		INSERT INTO DETALLE_POLICIA(IdServicio,IdMunicipalidad,IdPolicia,IdDelicuencial)
		VALUES(@AUXISERVI,1,@IDPOLICIA,@AUXIDELIN)

		INSERT INTO CONTROL__PERSECUCCION(IdServicio,IdMunicipalidad,IdDelicuencial,Detalle,CodOperación)
			VALUES(@AUXISERVI,1,@AUXIDELIN,@DETALLE,@CODOPERACION)
					
					PRINT 'SERVICIO DE CONTROL Y/O PRESECUCCIÓN REGISTRADO'
						RETURN 

END

ELSE

BEGIN
	PRINT 'EL SERVICIO DE CONTROL Y/O PRESECUCCIÓN YA EXISTE'
	 RETURN
END

SELECT*FROM CONTROL__PERSECUCCION
